
package edu.kit.ipd.sdq.kampws.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-10-26T11:10:56.007+02:00
 * Generated source version: 3.0.3
 * 
 */
public final class ChangeSpecificDependencies_ChangeSpecificDependenciesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.kampws.sdq.ipd.kit.edu/", "ChangeSpecificDependenciesService");

    private ChangeSpecificDependencies_ChangeSpecificDependenciesPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ChangeSpecificDependenciesService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ChangeSpecificDependenciesService ss = new ChangeSpecificDependenciesService(wsdlURL, SERVICE_NAME);
        ChangeSpecificDependencies port = ss.getChangeSpecificDependenciesPort();  
        
        {
        System.out.println("Invoking getBuildSpecificationPaths...");
        edu.kit.ipd.sdq.kampws.client.StringArray _getBuildSpecificationPaths_arg0 = null;
        try {
            edu.kit.ipd.sdq.kampws.client.StringArray _getBuildSpecificationPaths__return = port.getBuildSpecificationPaths(_getBuildSpecificationPaths_arg0);
            System.out.println("getBuildSpecificationPaths.result=" + _getBuildSpecificationPaths__return);

        } catch (IllegalArgumentException_Exception e) { 
            System.out.println("Expected exception: IllegalArgumentException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getChangeSpecificDependencies...");
        edu.kit.ipd.sdq.kampws.client.StringArray _getChangeSpecificDependencies_arg0 = null;
        try {
            edu.kit.ipd.sdq.kampws.client.StringArray _getChangeSpecificDependencies__return = port.getChangeSpecificDependencies(_getChangeSpecificDependencies_arg0);
            System.out.println("getChangeSpecificDependencies.result=" + _getChangeSpecificDependencies__return);

        } catch (IllegalArgumentException_Exception e) { 
            System.out.println("Expected exception: IllegalArgumentException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getChangeScenarios...");
        java.lang.String _getChangeScenarios_arg0 = "";
        try {
            edu.kit.ipd.sdq.kampws.client.StringArray _getChangeScenarios__return = port.getChangeScenarios(_getChangeScenarios_arg0);
            System.out.println("getChangeScenarios.result=" + _getChangeScenarios__return);

        } catch (IllegalArgumentException_Exception e) { 
            System.out.println("Expected exception: IllegalArgumentException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPossibleProjectNames...");
        edu.kit.ipd.sdq.kampws.client.StringArray _getPossibleProjectNames__return = port.getPossibleProjectNames();
        System.out.println("getPossibleProjectNames.result=" + _getPossibleProjectNames__return);


        }

        System.exit(0);
    }

}
