package edu.kit.ipd.sdq.kampws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-10-26T11:10:56.043+02:00
 * Generated source version: 3.0.3
 * 
 */
@WebServiceClient(name = "ChangeSpecificDependenciesService", 
                  wsdlLocation = "file:/D:/THESIS/Repository/trunk/Code-Abgabe/kamp-ws-parent/kamp-ws-client/target/wsdl/ChangeSpecificDependencies.wsdl",
                  targetNamespace = "http://server.kampws.sdq.ipd.kit.edu/") 
public class ChangeSpecificDependenciesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.kampws.sdq.ipd.kit.edu/", "ChangeSpecificDependenciesService");
    public final static QName ChangeSpecificDependenciesPort = new QName("http://server.kampws.sdq.ipd.kit.edu/", "ChangeSpecificDependenciesPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/THESIS/Repository/trunk/Code-Abgabe/kamp-ws-parent/kamp-ws-client/target/wsdl/ChangeSpecificDependencies.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ChangeSpecificDependenciesService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/THESIS/Repository/trunk/Code-Abgabe/kamp-ws-parent/kamp-ws-client/target/wsdl/ChangeSpecificDependencies.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ChangeSpecificDependenciesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ChangeSpecificDependenciesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChangeSpecificDependenciesService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ChangeSpecificDependenciesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ChangeSpecificDependenciesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ChangeSpecificDependenciesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ChangeSpecificDependencies
     */
    @WebEndpoint(name = "ChangeSpecificDependenciesPort")
    public ChangeSpecificDependencies getChangeSpecificDependenciesPort() {
        return super.getPort(ChangeSpecificDependenciesPort, ChangeSpecificDependencies.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChangeSpecificDependencies
     */
    @WebEndpoint(name = "ChangeSpecificDependenciesPort")
    public ChangeSpecificDependencies getChangeSpecificDependenciesPort(WebServiceFeature... features) {
        return super.getPort(ChangeSpecificDependenciesPort, ChangeSpecificDependencies.class, features);
    }

}
