
package edu.kit.ipd.sdq.kampws.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-10-26T11:10:56.036+02:00
 * Generated source version: 3.0.3
 */

@WebFault(name = "IllegalArgumentException", targetNamespace = "http://server.kampws.sdq.ipd.kit.edu/")
public class IllegalArgumentException_Exception extends Exception {
    
    private edu.kit.ipd.sdq.kampws.client.IllegalArgumentException illegalArgumentException;

    public IllegalArgumentException_Exception() {
        super();
    }
    
    public IllegalArgumentException_Exception(String message) {
        super(message);
    }
    
    public IllegalArgumentException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IllegalArgumentException_Exception(String message, edu.kit.ipd.sdq.kampws.client.IllegalArgumentException illegalArgumentException) {
        super(message);
        this.illegalArgumentException = illegalArgumentException;
    }

    public IllegalArgumentException_Exception(String message, edu.kit.ipd.sdq.kampws.client.IllegalArgumentException illegalArgumentException, Throwable cause) {
        super(message, cause);
        this.illegalArgumentException = illegalArgumentException;
    }

    public edu.kit.ipd.sdq.kampws.client.IllegalArgumentException getFaultInfo() {
        return this.illegalArgumentException;
    }
}
